### ISSUE TITLE
worker_wrapper - ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'

### ISSUE THREAD

**Issue by mdouchin** [opengisch/QFieldCloud#1016]
I am running a fresh master built yesterday, with the local configuration (on my laptop) and I encounter the following error in the qfieldcloud-worker_wrapper container, which causes it to restart every minute

```log
docker compose logs worker_wrapper 

worker_wrapper-1  | Traceback (most recent call last):
worker_wrapper-1  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
worker_wrapper-1  |     return _run_code(code, main_globals, None,
worker_wrapper-1  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
worker_wrapper-1  |     exec(code, run_globals)
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/debugpy/__main__.py", line 71, in <module>
worker_wrapper-1  |     cli.main()
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/debugpy/server/cli.py", line 486, in main
worker_wrapper-1  |     run()
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/debugpy/server/cli.py", line 336, in run_file
worker_wrapper-1  |     runpy.run_path(target, run_name="__main__")
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
worker_wrapper-1  |     return _run_module_code(code, init_globals, run_name,
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
worker_wrapper-1  |     _run_code(code, mod_globals, init_globals,
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
worker_wrapper-1  |     exec(code, run_globals)
worker_wrapper-1  |   File "manage.py", line 20, in <module>
worker_wrapper-1  |     main()
worker_wrapper-1  |   File "manage.py", line 16, in main
worker_wrapper-1  |     execute_from_command_line(sys.argv)
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
worker_wrapper-1  |     utility.execute()
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
worker_wrapper-1  |     django.setup()
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
worker_wrapper-1  |     apps.populate(settings.INSTALLED_APPS)
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 114, in populate
worker_wrapper-1  |     app_config.import_models()
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 301, in import_models
worker_wrapper-1  |     self.models_module = import_module(models_module_name)
worker_wrapper-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
worker_wrapper-1  |     return _bootstrap._gcd_import(name[level:], package, level)
worker_wrapper-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
worker_wrapper-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
worker_wrapper-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
worker_wrapper-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
worker_wrapper-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
worker_wrapper-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
worker_wrapper-1  |   File "/usr/src/app/qfieldcloud/core/models.py", line 28, in <module>
worker_wrapper-1  |     from qfieldcloud.core import geodb_utils, utils, validators
worker_wrapper-1  |   File "/usr/src/app/qfieldcloud/core/utils.py", line 11, in <module>
worker_wrapper-1  |     import boto3
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/boto3/__init__.py", line 16, in <module>
worker_wrapper-1  |     from boto3.session import Session
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
worker_wrapper-1  |     import botocore.session
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/session.py", line 29, in <module>
worker_wrapper-1  |     import botocore.credentials
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/credentials.py", line 34, in <module>
worker_wrapper-1  |     from botocore.config import Config
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/config.py", line 16, in <module>
worker_wrapper-1  |     from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 22, in <module>
worker_wrapper-1  |     from botocore.awsrequest import create_request_object
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/awsrequest.py", line 24, in <module>
worker_wrapper-1  |     import botocore.utils
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/utils.py", line 32, in <module>
worker_wrapper-1  |     import botocore.httpsession
worker_wrapper-1  |   File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 10, in <module>
worker_wrapper-1  |     from urllib3.util.ssl_ import (
worker_wrapper-1  | ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py)
worker_wrapper-1  | Waiting for postgres...
worker_wrapper-1  | Postgres is ready! ✨ 💅

```

Is it a known issue ? I will investigate more, but if anyone has already encountered this error, thanks in advance for clues.

**Comment by mdouchin** [comment]
Perhaps linked to fed1f11fea62bfd361e768329229ab00c81f7345 ?
