### ISSUE TITLE
Sentry pollutes local dev traces

### ISSUE THREAD

**Issue by olivierdalang** [opengisch/qfieldcloud#20]
On local dev, Sentry pollutes the errors logs quite a lot (see example)

Isn't there a way to have sentry setup on local dev (like we do with smpt4dev), or otherwise can't we completely disable it on local dev ?

```
orchestrator_1   | --- Logging error ---
orchestrator_1   | Traceback (most recent call last):
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1008, in perform_job
orchestrator_1   |     rv = job.perform()
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 706, in perform
orchestrator_1   |     self._result = self._execute()
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 729, in _execute
orchestrator_1   |     result = self.func(*self.args, **self.kwargs)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 219, in func
orchestrator_1   |     return import_attribute(self.func_name)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/utils.py", line 130, in import_attribute
orchestrator_1   |     return getattr(module, attribute)
orchestrator_1   | AttributeError: module 'orchestrator' has no attribute 'apply_deltas'
orchestrator_1   |
orchestrator_1   | During handling of the above exception, another exception occurred:
orchestrator_1   |
orchestrator_1   | Traceback (most recent call last):
orchestrator_1   |   File "/usr/src/app/orchestrator/worker.py", line 31, in handle_exception
orchestrator_1   |     job_row = get_job_row(job.id)
orchestrator_1   |   File "/usr/src/app/orchestrator/db_utils.py", line 77, in get_job_row
orchestrator_1   |     cur.execute(
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/psycopg2/extras.py", line 146, in execute
orchestrator_1   |     return super(DictCursor, self).execute(query, vars)
orchestrator_1   | psycopg2.errors.UndefinedTable: relation "core_job" does not exist
orchestrator_1   | LINE 3:             FROM core_job j
orchestrator_1   |                          ^
orchestrator_1   |
orchestrator_1   |
orchestrator_1   | During handling of the above exception, another exception occurred:
orchestrator_1   |
orchestrator_1   | Traceback (most recent call last):
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
orchestrator_1   |     msg = self.format(record)
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
orchestrator_1   |     return fmt.format(record)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/json_log_formatter/__init__.py", line 62, in format
orchestrator_1   |     message = record.getMessage()
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
orchestrator_1   |     msg = msg % self.args
orchestrator_1   | TypeError: not all arguments converted during string formatting
orchestrator_1   | Call stack:
orchestrator_1   |   File "/usr/local/lib/python3.8/runpy.py", line 192, in _run_module_as_main
orchestrator_1   |     return _run_code(code, main_globals, None,
orchestrator_1   |   File "/usr/local/lib/python3.8/runpy.py", line 85, in _run_code
orchestrator_1   |     exec(code, run_globals)
orchestrator_1   |   File "/usr/src/app/orchestrator/__main__.py", line 1, in <module>
orchestrator_1   |     from . import worker  # noqa
orchestrator_1   |   File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
orchestrator_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
orchestrator_1   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
orchestrator_1   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
orchestrator_1   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
orchestrator_1   |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
orchestrator_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
orchestrator_1   |   File "/usr/src/app/orchestrator/worker.py", line 56, in <module>
orchestrator_1   |     w.work()
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 590, in work
orchestrator_1   |     self.execute_job(job, queue)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 838, in execute_job
orchestrator_1   |     self.fork_work_horse(job, queue)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 755, in fork_work_horse
orchestrator_1   |     self.main_work_horse(job, queue)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 852, in main_work_horse
orchestrator_1   |     self.perform_job(job, queue)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/rq.py", line 74, in sentry_patched_perform_job 
orchestrator_1   |     rv = old_perform_job(self, job, *args, **kwargs)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1024, in perform_job
orchestrator_1   |     self.handle_exception(job, *exc_info)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/rq.py", line 93, in sentry_patched_handle_exception
orchestrator_1   |     return old_handle_exception(self, job, *exc_info, **kwargs)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1059, in handle_exception
orchestrator_1   |     fallthrough = handler(job, *exc_info)
orchestrator_1   |   File "/usr/src/app/orchestrator/worker.py", line 43, in handle_exception
orchestrator_1   |     logging.critical("Failed to handle exception: ", str(err))
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 2022, in critical
orchestrator_1   |     root.critical(msg, *args, **kwargs)
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1481, in critical
orchestrator_1   |     self._log(CRITICAL, msg, args, **kwargs)
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1577, in _log
orchestrator_1   |     self.handle(record)
orchestrator_1   |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
orchestrator_1   |     self.callHandlers(record)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/logging.py", line 86, in sentry_patched_callhandlers       
orchestrator_1   |     return old_callhandlers(self, record)
orchestrator_1   | Message: 'Failed to handle exception: '
orchestrator_1   | Arguments: ('relation "core_job" does not exist\nLINE 3:             FROM core_job j\n                         ^\n',)
```

instead of more readable

```
orchestrator_1   | Traceback (most recent call last):
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1008, in perform_job
orchestrator_1   |     rv = job.perform()
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 706, in perform
orchestrator_1   |     self._result = self._execute()
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 729, in _execute
orchestrator_1   |     result = self.func(*self.args, **self.kwargs)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 219, in func
orchestrator_1   |     return import_attribute(self.func_name)
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/rq/utils.py", line 130, in import_attribute
orchestrator_1   |     return getattr(module, attribute)
orchestrator_1   | AttributeError: module 'orchestrator' has no attribute 'apply_deltas'
orchestrator_1   |
orchestrator_1   | During handling of the above exception, another exception occurred:
orchestrator_1   |
orchestrator_1   | Traceback (most recent call last):
orchestrator_1   |   File "/usr/src/app/orchestrator/worker.py", line 31, in handle_exception
orchestrator_1   |     job_row = get_job_row(job.id)
orchestrator_1   |   File "/usr/src/app/orchestrator/db_utils.py", line 77, in get_job_row
orchestrator_1   |     cur.execute(
orchestrator_1   |   File "/usr/local/lib/python3.8/site-packages/psycopg2/extras.py", line 146, in execute
orchestrator_1   |     return super(DictCursor, self).execute(query, vars)
orchestrator_1   | psycopg2.errors.UndefinedTable: relation "core_job" does not exist
orchestrator_1   | LINE 3:             FROM core_job j
```

**Comment by suricactus** [comment]
As far as I see, this is no longer the case, I get a nice and clear error stack:

```
app_1                          |   Exception (ERROR):
app_1                          |   Traceback (most recent call last):
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
app_1                          |     response = get_response(request)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 183, in _get_response
app_1                          |     response = self.process_exception_by_middleware(e, request)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 339, in process_exception_by_middleware
app_1                          |     response = middleware_method(request, exception)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/middleware.py", line 110, in sentry_wrapped_method
app_1                          |     return old_method(*args, **kwargs)
app_1                          |       File "/usr/src/app/qfieldcloud/core/middleware/request_response_log.py", line 133, in process_exception
app_1                          |     raise exception
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
app_1                          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
app_1                          |     return callback(request, *args, **kwargs)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
app_1                          |     return self.dispatch(request, *args, **kwargs)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
app_1                          |     return bound_method(*args, **kwargs)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
app_1                          |     return view_func(request, *args, **kwargs)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
app_1                          |     return bound_method(*args, **kwargs)
app_1                          |       File "/usr/src/app/qfieldcloud/core/permission_check.py", line 26, in decorator
app_1                          |     return func(request, *args, **kwargs)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
app_1                          |     return handler(request, *args, **kwargs)
app_1                          |       File "/usr/src/app/qfieldcloud/web/views/settings_views.py", line 900, in post
app_1                          |     return self.create_team_members(self.request)
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
app_1                          |     return bound_method(*args, **kwargs)
app_1                          |       File "/usr/src/app/qfieldcloud/core/permission_check.py", line 26, in decorator
app_1                          |     return func(request, *args, **kwargs)
app_1                          |       File "/usr/src/app/qfieldcloud/web/views/settings_views.py", line 935, in create_team_members
app_1                          |     team_member.full_clean()
app_1                          |       File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1236, in full_clean
app_1                          |     self.clean()
app_1                          |       File "/usr/src/app/qfieldcloud/core/models.py", line 703, in clean
app_1                          |     print(d['asd'])
app_1                          |     KeyError: 'asd'

```
