### ISSUE TITLE
folder .qfieldsync - only reader 

### ISSUE THREAD

**Issue by robibrazze** [opengisch/qfieldcloud#427]
hi,
when i package layers (version of qgis 3.16.15), the plugin create folder .qfieldsync for sincro whit qfieldcloud that don't work well bacause the attibute of the folder is "only reader".
I tried manually to remove "only reader", but after save the modify the attribute retuned "only reader".
I think that the problem is win 11...

any help to solve?
Thanks a lot
Roberto

**Comment by suricactus** [comment]
Hi, @robibrazze . Does it produce a python error? Can you attach it here?

**Comment by robibrazze** [comment]
Hi, @suricactus,
the python error is this, Thanks a lot
2022-10-18T14:48:14     WARNING    Traceback (most recent call last):
              File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 253, in 
              reply.finished.connect(lambda: self.prepare_project_transfer())
              File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 343, in prepare_project_transfer
              self.project_transfer = CloudTransferrer(
              File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_transferrer.py", line 87, in __init__
              shutil.rmtree(self.temp_dir)
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 740, in rmtree
              return _rmtree_unsafe(path, onerror)
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 613, in _rmtree_unsafe
              _rmtree_unsafe(fullname, onerror)
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 622, in _rmtree_unsafe
              onerror(os.rmdir, path, sys.exc_info())
              File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\shutil.py", line 620, in _rmtree_unsafe
              os.rmdir(path)
             PermissionError: [WinError 5] Accesso negato: 'C:\\Users\\geomb\\Documents\\UFFICIO\\GIS\\FINALE-prove\\Finale_test_1\\test_cloud_finale\\.qfieldsync\\backup'

**Comment by suricactus** [comment]
Also please note your QGIS version is way too old and no longer supported, can you try with QGIS 3.26 and confirm you can reproduce the error?

**Comment by robibrazze** [comment]
Hi, i tried whit QGIS version 3.26 but the errore is the same, see below.


2022-10-19T14:37:32     WARNING    Traceback (most recent call last):
              File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 253, in 
              reply.finished.connect(lambda: self.prepare_project_transfer())
              File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_transfer_dialog.py", line 343, in prepare_project_transfer
              self.project_transfer = CloudTransferrer(
              File "C:\Users/geomb/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_transferrer.py", line 87, in __init__
              shutil.rmtree(self.temp_dir)
              File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\shutil.py", line 740, in rmtree
              return _rmtree_unsafe(path, onerror)
              File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\shutil.py", line 613, in _rmtree_unsafe
              _rmtree_unsafe(fullname, onerror)
              File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\shutil.py", line 622, in _rmtree_unsafe
              onerror(os.rmdir, path, sys.exc_info())
              File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\shutil.py", line 620, in _rmtree_unsafe
              os.rmdir(path)
             PermissionError: [WinError 5] Accesso negato: 'C:\\Users\\geomb\\Documents\\UFFICIO\\GIS\\FINALE-prove\\Finale_test_1\\test_cloud_finale\\.qfieldsync\\backup'

**Comment by suricactus** [comment]
@robibrazze isi this still an issue?
