### ISSUE TITLE
Invalid Job when pulling project in app

### ISSUE THREAD

**Issue by Oli22** [opengisch/qfieldcloud#756]
All my packaging jobs on a self hosted instance are finishing, but when trying to pull the project in the app I always get the following error:

ERROR Invalid job | request_id=none ts=2023-07-30T17:14:33.277050 name=root filename=rest_utils.py lineno=41 thread=140156003858176 source=app exc_info=Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/app/qfieldcloud/core/views/package_views.py", line 103, in get
    raise exceptions.InvalidJobError("Empty project package.")
qfieldcloud.core.exceptions.InvalidJobError: Invalid job 
Bad Request: /api/v1/packages/56a1273d-c673-4121-82d7-8688d2d277cc/latest/
WARNING Bad Request: /api/v1/packages/56a1273d-c673-4121-82d7-8688d2d277cc/latest/ | status_code=400 request=<WSGIRequest: GET '/api/v1/packages/56a1273d-c673-4121-82d7-8688d2d277cc/latest/'> request_id=none ts=2023-07-30T17:14:33.376854 name=django.request filename=log.py lineno=224 thread=140156003858176 source=app 

What do I do wrong?

**Comment by shapley** [comment]
I've got a similar issue. Can't download from self-hosted server. 

![similar_issue](https://github.com/user-attachments/assets/b6f4e8fd-b655-4207-bdce-a8d8795c20fe)

**Comment by shapley** [comment]
I have the same issue. Downloading from self-hosted instance with '.env' default settings.

![similar_issue](https://github.com/user-attachments/assets/d0998923-04a7-4ebb-8e94-44464e3a8e02)
