### ISSUE TITLE
remaining_trial_organizations error on setup

### ISSUE THREAD

**Issue by Oli22** [opengisch/qfieldcloud#779]
When trying to setup the project as described in the readme for current master you get following error on creating the superuser by
`docker compose run app python manage.py createsuperuser --username super_user --email super@user.com`

Everything is migrated fresh on a new install.

Traceback (most recent call last):
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 691, in get_or_create_current_subscription
    subscription = cls.objects.current().get(account_id=account.pk)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
qfieldcloud.subscription.models.Subscription.DoesNotExist: Subscription matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 21, in <module>
    main()
  File "/usr/src/app/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 163, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 146, in _create_user
    user.save(using=self._db)
  File "/usr/src/app/qfieldcloud/core/models.py", line 310, in save
    Subscription.get_or_create_current_subscription(account)
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 693, in get_or_create_current_subscription
    subscription = cls.create_default_plan_subscription(account)
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 781, in create_default_plan_subscription
    _trial_subscription, regular_subscription = cls.create_subscription(
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 858, in create_subscription
    created_by.save(update_fields=["remaining_trial_organizations"])
  File "/usr/src/app/qfieldcloud/core/models.py", line 312, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 722, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: remaining_trial_organizations

**Comment by HeatherHillers** [comment]
In my test deployment, I have "solved" the problem by replacing the 2 lines in models.py (see stack trace: line 858 and also a second such line) with created_by.save().  Then run docker compose -d --build again.  It's not the real answer, but it will get the project going until an update comes.  I was able to add superuser after this and launch the admin site.

**Comment by suricactus** [comment]
This should have been fixed by now, thanks for reporting.
