### ISSUE TITLE
Error when creating Django's superuser

### ISSUE THREAD

**Issue by gounux** [opengisch/qfieldcloud#801]
Hello,

I am trying to set up a custom instance of QFieldCloud, and meet the following error when creating the Django super user with the command `docker compose run app python manage.py createsuperuser --username admin --email admin@admin.com`

This stacktrace is:

```
Waiting for postgres...
Postgres is ready! ✨ 💅
Waiting for redis...
Waiting for redis...
Redis is ready! ✨ 💅
{"request_id":"none","ts":"2023-10-04T11:50:35.742121","level":"INFO","name":"axes.apps","message":"AXES: BEGIN version 5.40.1, blocking by username only","filename":"apps.py","lineno":42,"thread":140286725265216,"source":"app"}
Password: 
Password (again): 
Traceback (most recent call last):
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 690, in get_or_create_current_subscription
    subscription = cls.objects.current().get(account_id=account.pk)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
qfieldcloud.subscription.models.Subscription.DoesNotExist: Subscription matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 21, in <module>
    main()
  File "/usr/src/app/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 189, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 163, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/models.py", line 146, in _create_user
    user.save(using=self._db)
  File "/usr/src/app/qfieldcloud/core/models.py", line 310, in save
    Subscription.get_or_create_current_subscription(account)
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 692, in get_or_create_current_subscription
    subscription = cls.create_default_plan_subscription(account)
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 782, in create_default_plan_subscription
    _trial_subscription, regular_subscription = cls.create_subscription(
  File "/usr/src/app/qfieldcloud/subscription/models.py", line 860, in create_subscription
    created_by.save(update_fields=["remaining_trial_organizations"])
  File "/usr/src/app/qfieldcloud/core/models.py", line 312, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 722, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: remaining_trial_organizations
```

The database image used is `postgis/postgis:13-3.1`, migrations have been launched before.

This error was met on `v0.22.2`, after downgrading to `v0.20.0` it does not appear anymore (after having restarted with a fresh empty storage database set up with v0.20.0's migrations)

**Comment by Gagobert** [comment]
Yes, this is exactly the issue i'm having aswell - i have worked around it by exchanging two lines in the subscriptions/models.py script with "created_by.save()"  as explained in issue #779 ...unfortunately this is just a workaround, since it produces the error, that users can't see their projects, because they don't have an active subscription. 
I guess a workaround for that would be to change database entries in the qfieldcloud_db as explained in issue #668
a "real" fix, would be appreciated - please fix.

**Comment by suricactus** [comment]
Hey, both. The issue will be fixed soon as we merge. Thanks for reporting. https://github.com/opengisch/qfieldcloud/pull/797
